// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: stropt/testproto/test.proto

package testproto

import (
	_ "github.com/sryoya/protoreflet-go-examples/protobuf/stroptpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageFixedLen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value    string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	IntValue int32  `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3" json:"int_value,omitempty"` // irrevant field, in order to check if non-string field
}

func (x *MessageFixedLen) Reset() {
	*x = MessageFixedLen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stropt_testproto_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageFixedLen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageFixedLen) ProtoMessage() {}

func (x *MessageFixedLen) ProtoReflect() protoreflect.Message {
	mi := &file_stropt_testproto_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageFixedLen.ProtoReflect.Descriptor instead.
func (*MessageFixedLen) Descriptor() ([]byte, []int) {
	return file_stropt_testproto_test_proto_rawDescGZIP(), []int{0}
}

func (x *MessageFixedLen) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *MessageFixedLen) GetIntValue() int32 {
	if x != nil {
		return x.IntValue
	}
	return 0
}

type MessageMaxMinLen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *MessageMaxMinLen) Reset() {
	*x = MessageMaxMinLen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stropt_testproto_test_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageMaxMinLen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageMaxMinLen) ProtoMessage() {}

func (x *MessageMaxMinLen) ProtoReflect() protoreflect.Message {
	mi := &file_stropt_testproto_test_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageMaxMinLen.ProtoReflect.Descriptor instead.
func (*MessageMaxMinLen) Descriptor() ([]byte, []int) {
	return file_stropt_testproto_test_proto_rawDescGZIP(), []int{1}
}

func (x *MessageMaxMinLen) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type MessageInvalidMaxMinLen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *MessageInvalidMaxMinLen) Reset() {
	*x = MessageInvalidMaxMinLen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stropt_testproto_test_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageInvalidMaxMinLen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageInvalidMaxMinLen) ProtoMessage() {}

func (x *MessageInvalidMaxMinLen) ProtoReflect() protoreflect.Message {
	mi := &file_stropt_testproto_test_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageInvalidMaxMinLen.ProtoReflect.Descriptor instead.
func (*MessageInvalidMaxMinLen) Descriptor() ([]byte, []int) {
	return file_stropt_testproto_test_proto_rawDescGZIP(), []int{2}
}

func (x *MessageInvalidMaxMinLen) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type MessageMinLen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *MessageMinLen) Reset() {
	*x = MessageMinLen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stropt_testproto_test_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageMinLen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageMinLen) ProtoMessage() {}

func (x *MessageMinLen) ProtoReflect() protoreflect.Message {
	mi := &file_stropt_testproto_test_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageMinLen.ProtoReflect.Descriptor instead.
func (*MessageMinLen) Descriptor() ([]byte, []int) {
	return file_stropt_testproto_test_proto_rawDescGZIP(), []int{3}
}

func (x *MessageMinLen) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type MessageMaxLen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *MessageMaxLen) Reset() {
	*x = MessageMaxLen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stropt_testproto_test_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageMaxLen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageMaxLen) ProtoMessage() {}

func (x *MessageMaxLen) ProtoReflect() protoreflect.Message {
	mi := &file_stropt_testproto_test_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageMaxLen.ProtoReflect.Descriptor instead.
func (*MessageMaxLen) Descriptor() ([]byte, []int) {
	return file_stropt_testproto_test_proto_rawDescGZIP(), []int{4}
}

func (x *MessageMaxLen) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ParentMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Child *ChildMessage `protobuf:"bytes,1,opt,name=child,proto3" json:"child,omitempty"`
}

func (x *ParentMessage) Reset() {
	*x = ParentMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stropt_testproto_test_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParentMessage) ProtoMessage() {}

func (x *ParentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_stropt_testproto_test_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParentMessage.ProtoReflect.Descriptor instead.
func (*ParentMessage) Descriptor() ([]byte, []int) {
	return file_stropt_testproto_test_proto_rawDescGZIP(), []int{5}
}

func (x *ParentMessage) GetChild() *ChildMessage {
	if x != nil {
		return x.Child
	}
	return nil
}

type ChildMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ChildMessage) Reset() {
	*x = ChildMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stropt_testproto_test_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChildMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChildMessage) ProtoMessage() {}

func (x *ChildMessage) ProtoReflect() protoreflect.Message {
	mi := &file_stropt_testproto_test_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChildMessage.ProtoReflect.Descriptor instead.
func (*ChildMessage) Descriptor() ([]byte, []int) {
	return file_stropt_testproto_test_proto_rawDescGZIP(), []int{6}
}

func (x *ChildMessage) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type MessageStrOptOnInt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *MessageStrOptOnInt) Reset() {
	*x = MessageStrOptOnInt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stropt_testproto_test_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageStrOptOnInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageStrOptOnInt) ProtoMessage() {}

func (x *MessageStrOptOnInt) ProtoReflect() protoreflect.Message {
	mi := &file_stropt_testproto_test_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageStrOptOnInt.ProtoReflect.Descriptor instead.
func (*MessageStrOptOnInt) Descriptor() ([]byte, []int) {
	return file_stropt_testproto_test_proto_rawDescGZIP(), []int{7}
}

func (x *MessageStrOptOnInt) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type MessageWithList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListValues []string `protobuf:"bytes,1,rep,name=list_values,json=listValues,proto3" json:"list_values,omitempty"`
}

func (x *MessageWithList) Reset() {
	*x = MessageWithList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stropt_testproto_test_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageWithList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWithList) ProtoMessage() {}

func (x *MessageWithList) ProtoReflect() protoreflect.Message {
	mi := &file_stropt_testproto_test_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageWithList.ProtoReflect.Descriptor instead.
func (*MessageWithList) Descriptor() ([]byte, []int) {
	return file_stropt_testproto_test_proto_rawDescGZIP(), []int{8}
}

func (x *MessageWithList) GetListValues() []string {
	if x != nil {
		return x.ListValues
	}
	return nil
}

type MessageWithMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapValues map[int32]string `protobuf:"bytes,1,rep,name=map_values,json=mapValues,proto3" json:"map_values,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *MessageWithMap) Reset() {
	*x = MessageWithMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stropt_testproto_test_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageWithMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWithMap) ProtoMessage() {}

func (x *MessageWithMap) ProtoReflect() protoreflect.Message {
	mi := &file_stropt_testproto_test_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageWithMap.ProtoReflect.Descriptor instead.
func (*MessageWithMap) Descriptor() ([]byte, []int) {
	return file_stropt_testproto_test_proto_rawDescGZIP(), []int{9}
}

func (x *MessageWithMap) GetMapValues() map[int32]string {
	if x != nil {
		return x.MapValues
	}
	return nil
}

type MessageStrOptOnIntMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapValues map[int32]int32 `protobuf:"bytes,1,rep,name=map_values,json=mapValues,proto3" json:"map_values,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *MessageStrOptOnIntMap) Reset() {
	*x = MessageStrOptOnIntMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stropt_testproto_test_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageStrOptOnIntMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageStrOptOnIntMap) ProtoMessage() {}

func (x *MessageStrOptOnIntMap) ProtoReflect() protoreflect.Message {
	mi := &file_stropt_testproto_test_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageStrOptOnIntMap.ProtoReflect.Descriptor instead.
func (*MessageStrOptOnIntMap) Descriptor() ([]byte, []int) {
	return file_stropt_testproto_test_proto_rawDescGZIP(), []int{10}
}

func (x *MessageStrOptOnIntMap) GetMapValues() map[int32]int32 {
	if x != nil {
		return x.MapValues
	}
	return nil
}

var File_stropt_testproto_test_proto protoreflect.FileDescriptor

var file_stropt_testproto_test_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x73, 0x74, 0x72, 0x6f, 0x70, 0x74, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x74,
	0x65, 0x73, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x6f, 0x70, 0x74, 0x70, 0x62, 0x2f, 0x73, 0x74, 0x72, 0x6f,
	0x70, 0x74, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4c, 0x0a, 0x0f, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x46, 0x69, 0x78, 0x65, 0x64, 0x4c, 0x65, 0x6e, 0x12, 0x1c, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x06, 0xd2, 0xc7,
	0x19, 0x02, 0x08, 0x06, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69,
	0x6e, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x32, 0x0a, 0x10, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x4d, 0x61, 0x78, 0x4d, 0x69, 0x6e, 0x4c, 0x65, 0x6e, 0x12, 0x1e, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x08, 0xd2, 0xc7, 0x19,
	0x04, 0x10, 0x05, 0x18, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x39, 0x0a, 0x17,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x4d, 0x61,
	0x78, 0x4d, 0x69, 0x6e, 0x4c, 0x65, 0x6e, 0x12, 0x1e, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x08, 0xd2, 0xc7, 0x19, 0x04, 0x10, 0x03, 0x18, 0x05,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2d, 0x0a, 0x0d, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x4d, 0x69, 0x6e, 0x4c, 0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x06, 0xd2, 0xc7, 0x19, 0x02, 0x18, 0x03, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2d, 0x0a, 0x0d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x4d, 0x61, 0x78, 0x4c, 0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x06, 0xd2, 0xc7, 0x19, 0x02, 0x10, 0x05, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3e, 0x0a, 0x0d, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2d, 0x0a, 0x05, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x05,
	0x63, 0x68, 0x69, 0x6c, 0x64, 0x22, 0x2c, 0x0a, 0x0c, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x42, 0x06, 0xd2, 0xc7, 0x19, 0x02, 0x08, 0x06, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x32, 0x0a, 0x12, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x74,
	0x72, 0x4f, 0x70, 0x74, 0x4f, 0x6e, 0x49, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x06, 0xd2, 0xc7, 0x19, 0x02, 0x08, 0x06,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3a, 0x0a, 0x0f, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x57, 0x69, 0x74, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x0b, 0x6c, 0x69,
	0x73, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x42,
	0x06, 0xd2, 0xc7, 0x19, 0x02, 0x08, 0x06, 0x52, 0x0a, 0x6c, 0x69, 0x73, 0x74, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x22, 0x9f, 0x01, 0x0a, 0x0e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x57,
	0x69, 0x74, 0x68, 0x4d, 0x61, 0x70, 0x12, 0x4f, 0x0a, 0x0a, 0x6d, 0x61, 0x70, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x74, 0x65, 0x73,
	0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x57, 0x69,
	0x74, 0x68, 0x4d, 0x61, 0x70, 0x2e, 0x4d, 0x61, 0x70, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x42, 0x06, 0xd2, 0xc7, 0x19, 0x02, 0x08, 0x06, 0x52, 0x09, 0x6d, 0x61,
	0x70, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x1a, 0x3c, 0x0a, 0x0e, 0x4d, 0x61, 0x70, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xad, 0x01, 0x0a, 0x15, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x53, 0x74, 0x72, 0x4f, 0x70, 0x74, 0x4f, 0x6e, 0x49, 0x6e, 0x74, 0x4d, 0x61, 0x70, 0x12,
	0x56, 0x0a, 0x0a, 0x6d, 0x61, 0x70, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x74, 0x72, 0x4f, 0x70, 0x74, 0x4f, 0x6e, 0x49,
	0x6e, 0x74, 0x4d, 0x61, 0x70, 0x2e, 0x4d, 0x61, 0x70, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x42, 0x06, 0xd2, 0xc7, 0x19, 0x02, 0x08, 0x06, 0x52, 0x09, 0x6d, 0x61,
	0x70, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x1a, 0x3c, 0x0a, 0x0e, 0x4d, 0x61, 0x70, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x72, 0x79, 0x6f, 0x79, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x72, 0x65, 0x66, 0x6c, 0x65, 0x74, 0x2d, 0x67, 0x6f, 0x2d, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x73, 0x2f, 0x73, 0x74, 0x72, 0x6f, 0x70, 0x74, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stropt_testproto_test_proto_rawDescOnce sync.Once
	file_stropt_testproto_test_proto_rawDescData = file_stropt_testproto_test_proto_rawDesc
)

func file_stropt_testproto_test_proto_rawDescGZIP() []byte {
	file_stropt_testproto_test_proto_rawDescOnce.Do(func() {
		file_stropt_testproto_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_stropt_testproto_test_proto_rawDescData)
	})
	return file_stropt_testproto_test_proto_rawDescData
}

var file_stropt_testproto_test_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_stropt_testproto_test_proto_goTypes = []interface{}{
	(*MessageFixedLen)(nil),         // 0: testproto.MessageFixedLen
	(*MessageMaxMinLen)(nil),        // 1: testproto.MessageMaxMinLen
	(*MessageInvalidMaxMinLen)(nil), // 2: testproto.MessageInvalidMaxMinLen
	(*MessageMinLen)(nil),           // 3: testproto.MessageMinLen
	(*MessageMaxLen)(nil),           // 4: testproto.MessageMaxLen
	(*ParentMessage)(nil),           // 5: testproto.ParentMessage
	(*ChildMessage)(nil),            // 6: testproto.ChildMessage
	(*MessageStrOptOnInt)(nil),      // 7: testproto.MessageStrOptOnInt
	(*MessageWithList)(nil),         // 8: testproto.MessageWithList
	(*MessageWithMap)(nil),          // 9: testproto.MessageWithMap
	(*MessageStrOptOnIntMap)(nil),   // 10: testproto.MessageStrOptOnIntMap
	nil,                             // 11: testproto.MessageWithMap.MapValuesEntry
	nil,                             // 12: testproto.MessageStrOptOnIntMap.MapValuesEntry
}
var file_stropt_testproto_test_proto_depIdxs = []int32{
	6,  // 0: testproto.ParentMessage.child:type_name -> testproto.ChildMessage
	11, // 1: testproto.MessageWithMap.map_values:type_name -> testproto.MessageWithMap.MapValuesEntry
	12, // 2: testproto.MessageStrOptOnIntMap.map_values:type_name -> testproto.MessageStrOptOnIntMap.MapValuesEntry
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_stropt_testproto_test_proto_init() }
func file_stropt_testproto_test_proto_init() {
	if File_stropt_testproto_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stropt_testproto_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageFixedLen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stropt_testproto_test_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageMaxMinLen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stropt_testproto_test_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageInvalidMaxMinLen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stropt_testproto_test_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageMinLen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stropt_testproto_test_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageMaxLen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stropt_testproto_test_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParentMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stropt_testproto_test_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChildMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stropt_testproto_test_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageStrOptOnInt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stropt_testproto_test_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageWithList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stropt_testproto_test_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageWithMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stropt_testproto_test_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageStrOptOnIntMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stropt_testproto_test_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stropt_testproto_test_proto_goTypes,
		DependencyIndexes: file_stropt_testproto_test_proto_depIdxs,
		MessageInfos:      file_stropt_testproto_test_proto_msgTypes,
	}.Build()
	File_stropt_testproto_test_proto = out.File
	file_stropt_testproto_test_proto_rawDesc = nil
	file_stropt_testproto_test_proto_goTypes = nil
	file_stropt_testproto_test_proto_depIdxs = nil
}
