// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: protobuf/arbitrarymethod/arbitrarymethod.proto

package arbitrarymethod

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallAnyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FuncName string       `protobuf:"bytes,1,opt,name=func_name,json=funcName,proto3" json:"func_name,omitempty"`
	Params   []*anypb.Any `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty"`
}

func (x *CallAnyRequest) Reset() {
	*x = CallAnyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_arbitrarymethod_arbitrarymethod_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallAnyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallAnyRequest) ProtoMessage() {}

func (x *CallAnyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_arbitrarymethod_arbitrarymethod_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallAnyRequest.ProtoReflect.Descriptor instead.
func (*CallAnyRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_arbitrarymethod_arbitrarymethod_proto_rawDescGZIP(), []int{0}
}

func (x *CallAnyRequest) GetFuncName() string {
	if x != nil {
		return x.FuncName
	}
	return ""
}

func (x *CallAnyRequest) GetParams() []*anypb.Any {
	if x != nil {
		return x.Params
	}
	return nil
}

type CallAnyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*anypb.Any `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *CallAnyResponse) Reset() {
	*x = CallAnyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_arbitrarymethod_arbitrarymethod_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallAnyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallAnyResponse) ProtoMessage() {}

func (x *CallAnyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_arbitrarymethod_arbitrarymethod_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallAnyResponse.ProtoReflect.Descriptor instead.
func (*CallAnyResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_arbitrarymethod_arbitrarymethod_proto_rawDescGZIP(), []int{1}
}

func (x *CallAnyResponse) GetResults() []*anypb.Any {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_protobuf_arbitrarymethod_arbitrarymethod_proto protoreflect.FileDescriptor

var file_protobuf_arbitrarymethod_arbitrarymethod_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x72, 0x62, 0x69, 0x74,
	0x72, 0x61, 0x72, 0x79, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x2f, 0x61, 0x72, 0x62, 0x69, 0x74,
	0x72, 0x61, 0x72, 0x79, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0f, 0x61, 0x72, 0x62, 0x69, 0x74, 0x72, 0x61, 0x72, 0x79, 0x6d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5b, 0x0a, 0x0e,
	0x43, 0x61, 0x6c, 0x6c, 0x41, 0x6e, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x66, 0x75, 0x6e, 0x63, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e,
	0x79, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x41, 0x0a, 0x0f, 0x43, 0x61, 0x6c,
	0x6c, 0x41, 0x6e, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x07,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x41, 0x6e, 0x79, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x32, 0x60, 0x0a, 0x0e,
	0x43, 0x61, 0x6c, 0x6c, 0x41, 0x6e, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4e,
	0x0a, 0x07, 0x43, 0x61, 0x6c, 0x6c, 0x41, 0x6e, 0x79, 0x12, 0x1f, 0x2e, 0x61, 0x72, 0x62, 0x69,
	0x74, 0x72, 0x61, 0x72, 0x79, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x2e, 0x43, 0x61, 0x6c, 0x6c,
	0x41, 0x6e, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x61, 0x72, 0x62,
	0x69, 0x74, 0x72, 0x61, 0x72, 0x79, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x2e, 0x43, 0x61, 0x6c,
	0x6c, 0x41, 0x6e, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x40,
	0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x72, 0x79,
	0x6f, 0x79, 0x61, 0x2f, 0x72, 0x65, 0x66, 0x6c, 0x65, 0x63, 0x74, 0x2d, 0x67, 0x6f, 0x2d, 0x65,
	0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x61, 0x72, 0x62, 0x69, 0x74, 0x72, 0x61, 0x72, 0x79, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_arbitrarymethod_arbitrarymethod_proto_rawDescOnce sync.Once
	file_protobuf_arbitrarymethod_arbitrarymethod_proto_rawDescData = file_protobuf_arbitrarymethod_arbitrarymethod_proto_rawDesc
)

func file_protobuf_arbitrarymethod_arbitrarymethod_proto_rawDescGZIP() []byte {
	file_protobuf_arbitrarymethod_arbitrarymethod_proto_rawDescOnce.Do(func() {
		file_protobuf_arbitrarymethod_arbitrarymethod_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_arbitrarymethod_arbitrarymethod_proto_rawDescData)
	})
	return file_protobuf_arbitrarymethod_arbitrarymethod_proto_rawDescData
}

var file_protobuf_arbitrarymethod_arbitrarymethod_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_arbitrarymethod_arbitrarymethod_proto_goTypes = []interface{}{
	(*CallAnyRequest)(nil),  // 0: arbitrarymethod.CallAnyRequest
	(*CallAnyResponse)(nil), // 1: arbitrarymethod.CallAnyResponse
	(*anypb.Any)(nil),       // 2: google.protobuf.Any
}
var file_protobuf_arbitrarymethod_arbitrarymethod_proto_depIdxs = []int32{
	2, // 0: arbitrarymethod.CallAnyRequest.params:type_name -> google.protobuf.Any
	2, // 1: arbitrarymethod.CallAnyResponse.results:type_name -> google.protobuf.Any
	0, // 2: arbitrarymethod.CallAnyService.CallAny:input_type -> arbitrarymethod.CallAnyRequest
	1, // 3: arbitrarymethod.CallAnyService.CallAny:output_type -> arbitrarymethod.CallAnyResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protobuf_arbitrarymethod_arbitrarymethod_proto_init() }
func file_protobuf_arbitrarymethod_arbitrarymethod_proto_init() {
	if File_protobuf_arbitrarymethod_arbitrarymethod_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_arbitrarymethod_arbitrarymethod_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallAnyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_arbitrarymethod_arbitrarymethod_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallAnyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_arbitrarymethod_arbitrarymethod_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_arbitrarymethod_arbitrarymethod_proto_goTypes,
		DependencyIndexes: file_protobuf_arbitrarymethod_arbitrarymethod_proto_depIdxs,
		MessageInfos:      file_protobuf_arbitrarymethod_arbitrarymethod_proto_msgTypes,
	}.Build()
	File_protobuf_arbitrarymethod_arbitrarymethod_proto = out.File
	file_protobuf_arbitrarymethod_arbitrarymethod_proto_rawDesc = nil
	file_protobuf_arbitrarymethod_arbitrarymethod_proto_goTypes = nil
	file_protobuf_arbitrarymethod_arbitrarymethod_proto_depIdxs = nil
}
